name: Open notebooks in Kaggle

on:
  workflow_call:
    inputs:
      source_directory:
        description: "Source directory with the files to be processed"
        type: string
      work_directory:
        description: "Work directory with a copy of the files to be processed"
        type: string
      notebook_pattern:
        description: "Search pattern for notebooks to be processed"
        type: string
      extra_files_pattern:
        description: "Search pattern for extra files to be processed"
        type: string
      notebook_preparation:
        description: "Script to be run before processing notebooks"
        type: string
      extra_files_preparation:
        description: "Script to be run before processing extra files"
        type: string
      test_script:
        description: "Script to be run to test notebooks"
        type: string
      fem_on_kaggle_packages:
        description: "List of packages that need an installation cell among the one offered by FEM on Kaggle"
        type: string
      pip_packages:
        description: "List of pip-installable packages that need an installation cell"
        type: string
      source_from:
        description: "How to get the source files"
        type: string
      publish_on:
        description: "How to publish the processed notebooks"
        type: string
      publish_if_repository:
        description: "Restrict publishing to a specific calling repository"
        type: string
      publish_if_branch:
        description: "Restrict publishing to a specific branch on the calling repository"
        type: string
    secrets:
      RCLONE_CONFIG_DRIVE_CLIENT_ID:
        description: "Client ID for the Google Acccount. Only used when source_from and/or publish_on are drive"
      RCLONE_CONFIG_DRIVE_CLIENT_SECRET:
        description: "Secret for the Google Acccount. Only used when source_from and/or publish_on are drive"
      RCLONE_CONFIG_DRIVE_TOKEN:
        description: "Token for the Google Acccount. Only used when source_from and/or publish_on are drive"
      REPO_ACCESS_TOKEN:
        description: "Token that enables reading from the source repository and/or writing to the destination repository. Only used when source_from and/or publish_on are github"

jobs:
  run:
    runs-on: ubuntu-latest
    container: ghcr.io/fem-on-kaggle/base:latest
    steps:
      - name: Fetch updated package list
        run: apt update -y -q
      - name: Install apt dependencies of the workflow call library
        run: |
          apt install -y -qq imagemagick inkscape
          wget https://github.com/rclone/rclone/releases/download/v1.73.3/rclone-v1.73.3-linux-amd64.deb -O /tmp/rclone-v1.73.3-linux-amd64.deb
          dpkg -i /tmp/rclone-v1.73.3-linux-amd64.deb
      - name: Install uv
        uses: astral-sh/setup-uv@cec208311dfd045dd5311c1add060b2062131d57  # v8.0.0
      - name: Clone workflow call library
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          repository: fem-on-colab/open-in-colab-workflow.git
          ref: main
          path: _workflow_call_library
      - name: Install the workflow call library
        run: |
          pushd _workflow_call_library
          uv sync --no-dev --locked --no-editable
          mv .venv ..
          popd
          rm -rf _workflow_call_library
        shell: bash
      - name: Determine source settings
        id: determine_source
        run: |
          uv run python -m open_in_cloud_workflow.source_from "${{ inputs.source_from }}" > .source
          while read -r VARIABLE_VALUE; do
            VARIABLE_VALUE_ARRAY=(${VARIABLE_VALUE//=/ })
            echo "${VARIABLE_VALUE_ARRAY[0]}=${VARIABLE_VALUE_ARRAY[1]}" >> ${GITHUB_OUTPUT}
          done < .source
          rm .source
        shell: bash
      - name: Validate source directory
        run: |
          case "${{ inputs.source_directory }}" in
            ""|"."|"./" )
              echo "Invalid source_directory"
              exit 1
              ;;
          esac
      - name: Mark source directory as safe
        if: steps.determine_source.outputs.source == 'github'
        run: |
          git config --global --add safe.directory "${{ inputs.source_directory }}"
      - name: Clone GitHub repository of the source in the source directory
        if: steps.determine_source.outputs.source == 'github'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          repository: "${{ steps.determine_source.outputs.repository }}"
          token: "${{ secrets.REPO_ACCESS_TOKEN || github.token }}"
          ref: "${{ steps.determine_source.outputs.branch }}"
          path: "${{ inputs.source_directory }}"
          set-safe-directory: false
      - name: Download files from Google Drive in the source directory
        if: steps.determine_source.outputs.source == 'drive'
        run: |
          uv run python -m open_in_cloud_workflow.download_files_from_google_drive "${{ inputs.source_directory }}" "${{ inputs.notebook_pattern }}" "${{ inputs.source_from }}"
        env:
          RCLONE_CONFIG_DRIVE_CLIENT_ID: "${{ secrets.RCLONE_CONFIG_DRIVE_CLIENT_ID }}"
          RCLONE_CONFIG_DRIVE_CLIENT_SECRET: "${{ secrets.RCLONE_CONFIG_DRIVE_CLIENT_SECRET }}"
          RCLONE_CONFIG_DRIVE_TOKEN: "${{ secrets.RCLONE_CONFIG_DRIVE_TOKEN }}"
      - name: Determine publisher settings
        id: determine_publisher
        run: |
          uv run python -m open_in_cloud_workflow.publish_on "${{ inputs.publish_on }}" > .publisher
          while read -r VARIABLE_VALUE; do
            VARIABLE_VALUE_ARRAY=(${VARIABLE_VALUE//=/ })
            echo "${VARIABLE_VALUE_ARRAY[0]}=${VARIABLE_VALUE_ARRAY[1]}" >> ${GITHUB_OUTPUT}
          done < .publisher
          rm .publisher
        shell: bash
      - name: Determine publisher upload pattern
        run: |
          if [[ "${{ steps.determine_publisher.outputs.publisher }}" == "artifact" ]]; then
            UPLOAD_PATTERN_PREFIX="${{ inputs.work_directory }}/"
          else
            UPLOAD_PATTERN_PREFIX=""
          fi
          UPLOAD_PATTERN_ARRAY=()
          while read -r PATTERN; do
            UPLOAD_PATTERN_ARRAY+=("${UPLOAD_PATTERN_PREFIX}${PATTERN}")
          done <<< "${{ inputs.notebook_pattern }}"
          if [[ -n "${{ inputs.extra_files_pattern }}" ]]; then
            while read -r PATTERN; do
              UPLOAD_PATTERN_ARRAY+=("${UPLOAD_PATTERN_PREFIX}${PATTERN}")
            done <<< "${{ inputs.extra_files_pattern }}"
          fi
          SEPARATOR="\n"
          UPLOAD_PATTERN="$(printf "%s\n" "${UPLOAD_PATTERN_ARRAY[@]}")"
          {
            echo 'UPLOAD_PATTERN<<EOF'
            echo "${UPLOAD_PATTERN}"
            echo EOF
          } >> ${GITHUB_ENV}
        shell: bash
      - name: Validate work directory
        run: |
          case "${{ inputs.work_directory }}" in
            ""|"."|"./" )
              echo "Invalid work_directory"
              exit 1
              ;;
          esac
      - name: Mark work directory as safe
        if: steps.determine_publisher.outputs.publisher == 'github' && (github.repository == inputs.publish_if_repository || inputs.publish_if_repository == '') && (endsWith(github.ref, inputs.publish_if_branch) || inputs.publish_if_branch == '')
        run: |
          git config --global --add safe.directory "${{ inputs.work_directory }}"
      - name: Clone GitHub repository of the publisher in the work directory
        if: steps.determine_publisher.outputs.publisher == 'github' && (github.repository == inputs.publish_if_repository || inputs.publish_if_repository == '') && (endsWith(github.ref, inputs.publish_if_branch) || inputs.publish_if_branch == '')
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2
        with:
          repository: "${{ steps.determine_publisher.outputs.repository }}"
          token: "${{ secrets.REPO_ACCESS_TOKEN || github.token }}"
          ref: "${{ steps.determine_publisher.outputs.branch }}"
          fetch-depth: 0
          path: "${{ inputs.work_directory }}"
          set-safe-directory: false
      - name: Clean GitHub repository of the publisher in the work directory
        if: steps.determine_publisher.outputs.publisher == 'github' && (github.repository == inputs.publish_if_repository || inputs.publish_if_repository == '') && (endsWith(github.ref, inputs.publish_if_branch) || inputs.publish_if_branch == '')
        run: |
          pushd "${{ inputs.work_directory }}"
          UPLOAD_PATTERN_AS_ARRAY=($(echo "${{ env.UPLOAD_PATTERN }}" | sed "s/\n/ /g"))
          for UPLOAD_PATTERN_ENTRY in "${UPLOAD_PATTERN_AS_ARRAY[@]}"; do
            FILES=$(git ls-files $UPLOAD_PATTERN_ENTRY)
            if [[ -n "$FILES" ]]; then
              git rm -f $FILES
            fi
          done
          popd
        shell: bash
      - name: Run notebook preparation
        if: inputs.notebook_preparation != ''
        run: |
          ${{ inputs.notebook_preparation }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        shell: bash
      - name: Run extra files preparation
        if: inputs.extra_files_preparation != ''
        run: |
          ${{ inputs.extra_files_preparation }}
        env:
          GITHUB_TOKEN: ${{ github.token }}
        shell: bash
      - name: Add installation cells
        run: |
          uv run python -m open_in_cloud_workflow.add_installation_cells "${PWD}/${{ inputs.work_directory }}" "${{ inputs.notebook_pattern }}" "kaggle" '${{ inputs.fem_on_kaggle_packages }}' '${{ inputs.pip_packages }}'
      - name: Test notebooks in the work directory
        if: inputs.test_script != ''
        run: |
          export PYTHONPATH="/usr/lib/${PYTHON_VERSION}/test-task/extra-site-packages:${PYTHONPATH}"
          export LD_LIBRARY_PATH=""
          ${{ inputs.test_script }}
        shell: bash
      - name: Replace images in markdown in the work directory
        run: |
          uv run python -m open_in_cloud_workflow.replace_images_in_markdown "${PWD}/${{ inputs.work_directory }}" "${{ inputs.notebook_pattern }}"
      - name: Replace links in markdown
        run: |
          uv run python -m open_in_cloud_workflow.replace_links_in_markdown "${PWD}/${{ inputs.work_directory }}" "${{ inputs.notebook_pattern }}" "kaggle" "${{ inputs.publish_on }}"
        env:
          RCLONE_CONFIG_DRIVE_CLIENT_ID: "${{ secrets.RCLONE_CONFIG_DRIVE_CLIENT_ID }}"
          RCLONE_CONFIG_DRIVE_CLIENT_SECRET: "${{ secrets.RCLONE_CONFIG_DRIVE_CLIENT_SECRET }}"
          RCLONE_CONFIG_DRIVE_TOKEN: "${{ secrets.RCLONE_CONFIG_DRIVE_TOKEN }}"
      - name: Upload files in the work directory to an artifact
        if: steps.determine_publisher.outputs.publisher == 'artifact' && (success() || failure() || cancelled())
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f  # v7.0.0
        with:
          name: ${{ steps.determine_publisher.outputs.name }}
          path: ${{ env.UPLOAD_PATTERN }}
      - name: Upload files in the work directory to Google Drive
        if: steps.determine_publisher.outputs.publisher == 'drive' && (github.repository == inputs.publish_if_repository || inputs.publish_if_repository == '') && (endsWith(github.ref, inputs.publish_if_branch) || inputs.publish_if_branch == '')
        run: |
          uv run python -m open_in_cloud_workflow.upload_files_to_google_drive "${{ inputs.work_directory }}" "${{ env.UPLOAD_PATTERN }}" "${{ inputs.publish_on }}"
        env:
          RCLONE_CONFIG_DRIVE_CLIENT_ID: "${{ secrets.RCLONE_CONFIG_DRIVE_CLIENT_ID }}"
          RCLONE_CONFIG_DRIVE_CLIENT_SECRET: "${{ secrets.RCLONE_CONFIG_DRIVE_CLIENT_SECRET }}"
          RCLONE_CONFIG_DRIVE_TOKEN: "${{ secrets.RCLONE_CONFIG_DRIVE_TOKEN }}"
      - name: Upload files in the work directory to GitHub repository
        if: steps.determine_publisher.outputs.publisher == 'github' && (github.repository == inputs.publish_if_repository || inputs.publish_if_repository == '') && (endsWith(github.ref, inputs.publish_if_branch) || inputs.publish_if_branch == '')
        run: |
          pushd "${{ inputs.source_directory }}"
          SHA_SHORT=$(git rev-parse --short HEAD)
          popd
          pushd "${{ inputs.work_directory }}"
          UPLOAD_PATTERN_AS_ARRAY=($(echo "${{ env.UPLOAD_PATTERN }}" | sed "s/\n/ /g"))
          for UPLOAD_PATTERN_ENTRY in "${UPLOAD_PATTERN_AS_ARRAY[@]}"; do
            git add "${UPLOAD_PATTERN_ENTRY}"
          done
          if [[ "$(git diff --name-only --cached | wc -l)" -gt 0 ]]; then
            git config user.name "GitHub Actions"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            BRANCH="${{ steps.determine_publisher.outputs.branch }}"
            git pull origin ${BRANCH}
            git commit -m "deploy: ${GITHUB_REPOSITORY}@${SHA_SHORT}"
            git push origin ${BRANCH}
          fi
          popd
        shell: bash
